MACHINES = {
    :"rpm-repo" => {
        :box_name => "generic/centos9s",
        :cpus => 2,
        :memory => 1024,
    }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.provider "virtualbox" do |v|
                v.memory = boxconfig[:memory]
                v.cpus = boxconfig[:cpus]
            end

            # copy folder with sources
            config.vm.provision "file", source: "./files", destination: "/tmp/files"
            # provision script for building rpm package
            config.vm.provision "shell", path: "./00-rpm-build.sh"
            # provision script for repo setup
            config.vm.provision "shell", path: "./01-repo-setup.sh"
        end
    end
end
