# -*- mode: ruby -*- 
# vi: set ft=ruby : vsa

WORKER_NODES = {
  worker: {
    ip: "192.168.56.11",
  },
}


Vagrant.configure(2) do |config| 
  config.vm.box = "ubuntu/jammy64" 
  config.vm.provider "virtualbox" do |v| 
      v.memory = 512 
      v.cpus = 1
  end 

  WORKER_NODES.each do |node_name, node_data|
    config.vm.define node_name do |node| 
      node.vm.network "private_network", ip: node_data[:ip],  virtualbox__intnet: "net1" 
      node.vm.hostname = node_name
      node.vm.provision "shell", path: "provisioner-worker-node.sh"
    end
  end

  config.vm.define "control" do |node| 
    node.vm.network "private_network", ip: "192.168.56.10",  virtualbox__intnet: "net1" 
    node.vm.hostname = "control" 

    config.vm.provision "file", source: "./files/ansible", destination: "/tmp/keys/ansible"
    config.vm.provision "file", source: "./files/ansible.pub", destination: "/tmp/keys/ansible.pub"
    config.vm.provision "file", source: "./playbooks", destination: "/tmp/playbooks"

    node.vm.provision "shell" do |s|
      # pass the ips of the worker nodes to the script
      ips =  WORKER_NODES.map { |k, v| v[:ip] }
      s.path = "provisioner-control-node.sh"
      s.args = ips
    end
  end
end 
