# -*- mode: ruby -*-
# vi: set ft=ruby :
# export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|

    config.vm.define "pxeserver" do |server|
      server.vm.box = "ubuntu/mantic64"
    
      server.vm.host_name = 'pxeserver'
      server.vm.network :private_network, ip: "192.168.56.1", virtualbox__intnet: 'pxenet'
      server.vm.network "forwarded_port", guest: 80, host: 18080
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

      server.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install ansible -y  

        cd /vagrant
        ansible-playbook -i="pxeserver," -c local ./playbook.yml
      SHELL
    end


    config.vm.define "pxeclient" do |pxeclient|
      pxeclient.vm.box = 'ubuntu/mantic64'
      pxeclient.vm.host_name = 'pxeclient'
      pxeclient.vm.network :private_network, ip: "192.168.56.100", virtualbox__intnet: 'pxenet'
      pxeclient.vm.provider :virtualbox do |vb|
        vb.memory = "6144"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize [
            'modifyvm', :id,
            '--nic1', 'intnet',
            '--intnet1', 'pxenet',
            '--nic2', 'nat',
            '--boot1', 'net',
            '--boot2', 'none',
            '--boot3', 'none',
            '--boot4', 'none'
          ]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
            # ENABLE to fix memory issues
#     end

    end
  
    end
    