MACHINES = {
  :node1 => {
        :vm_name => "node1",
        :cpus => 2,
        :memory => 1024,
        :ip => "192.168.57.11",
  },
  :node2 => {
        :vm_name => "node2",
        :cpus => 2,
        :memory => 1024,
        :ip => "192.168.57.12",

  },
  :barman => {
        :vm_name => "barman",
        :cpus => 1,
        :memory => 1024,
        :ip => "192.168.57.13",

  },

}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
      box.vm.box = "ubuntu/mantic64"
      box.vm.host_name = boxconfig[:vm_name]
      box.vm.network "private_network", ip: boxconfig[:ip]
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      # # Запуск ansible-playbook
      if boxconfig[:vm_name] == "barman"
        box.vm.provision "ansible" do |ansible|
          ansible.playbook = "provisioning/playbook.yml"
          ansible.inventory_path = "provisioning/hosts.yml"
          ansible.host_key_checking = "false"
          ansible.become = "true"
          ansible.limit = "all"
          ansible.compatibility_mode = "2.0"
         end
      end
    end
  end
end
